name: card_repository
description: Dart package which develops model and repository to connect to scryfall api
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  http: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  plugin_platform_interface: ^2.1.4
