name: db_repository
description: Dart package which manages the db domain.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cache:
    path: ../cache
  equatable: ^2.0.5
  firebase_core: ^2.12.0
  cloud_firestore: ^4.9.1
  flutter:
    sdk: flutter

dev_dependencies:
  firebase_auth_platform_interface: ^6.15.0
  firebase_core_platform_interface: ^4.8.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  plugin_platform_interface: ^2.1.4
