// ignore_for_file: constant_identifier_names

const ERROR_DISPLAY_SECS = 10;
const CARD_BORDER_RADIUS = 12.0;

/// CARD SIZE SMALL DIMENSIONS
const CARD_WIDTH_S = 100.0;
const CARD_HEIGHT_S = (CARD_WIDTH_S * CARD_HEIGHT_INCH / CARD_WIDTH_INCH) +
    CARD_SIZE_CORRECTION_S;
const CARD_SIZE_CORRECTION_S = 16;
const CARD_BORDER_RADIUS_S = 3.0;

/// CARD SIZE MEDIUM_DIMENSIONS
const CARD_WIDTH_M = 196.0;
const CARD_HEIGHT_M = (CARD_WIDTH_M * CARD_HEIGHT_INCH / CARD_WIDTH_INCH) +
    CARD_SIZE_CORRECTION_M;
const CARD_SIZE_CORRECTION_M = 21;

const CARD_HEIGHT_INCH = 3.5;
const CARD_WIDTH_INCH = 2.5;

const CIRCLE_AVATAR_BUTTON_SIZE = 17.0;
const PADDING = 8.0;
